### ISSUE TITLE
Not enough batching

### ISSUE THREAD

**Issue by k-bx** [simonmar/haskell-eXchange-2015#1]
In [my fork](https://github.com/k-bx/haskell-eXchange-2015) (not sure if you'd be happy with a pull-request), if you build and run it (as per readme), you would get these results (for this Main.hs):

```
main :: IO ()
main = do
  putStrLn "hello world"
  res <- run $ (,) <$> mapM getPostContent [1..3] <*> mapM getPostContent [4..6]
  print res
```

```
➜  blog git:(master) ✗ stack exec blog
hello world
select postid,content from postcontent where postid in (4,1)
select postid,content from postcontent where postid in (5,2)
select postid,content from postcontent where postid in (6,3)
(["example content 1","example content 2","example content 3"],["example content 4","example content 5","example content 6"])
```

I haven't looked at it in-depth yet, but is this immediately obvious that that's because I use GHC 7.10 or is this something else? Thanks!

**Comment by simonmar** [comment]
You are likely using the wrong `mapM`.  Either use `traverse`, or define `mapM = traverse` somewhere.

**Comment by k-bx** [comment]
Thank you! It is the case indeed.
